version: "3.1"
services:
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASES=${MYSQL_DATABASES}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_MY_DATABASE=${MYSQL_MY_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data_mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  mongo:
    container_name: ${MONGO_CONTAINER_NAME}
    image: ${MONGO_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data_mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_CONTAINER_IMAGE_NAME}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
